### ISSUE TITLE
Tutorial for using bancor protocol

### ISSUE THREAD

**Issue by pavsh** [bancorprotocol/contracts-solidity#191]
Hi, can you please create a tutorial to explain how to use the bancor protocol with erc20 token? The documentation is very poor.

**Comment by pavsh** [comment]
A specialy for the bancor connector

**Comment by yudilevi** [comment]
Hey man,

We're working on some documentation and it should be available soon.

Thanks for the interest :)

**Comment by rluijk** [comment]
Hey, that is wonderful. Can you provide the link to the released documentation?

**Comment by yudilevi** [comment]
Sure, as soon as they are ready :)

**Comment by maxwolff** [comment]
bro

**Comment by akhavr** [comment]
Still no docs?

**Comment by yudilevi** [comment]
Sorry, not yet. We've been busy with new features.
We should have a basic setup instructions soon though.

**Comment by lbeder** [comment]
Please check https://docs.bancor.network/
