### ISSUE TITLE
Optimize transfers

### ISSUE THREAD

**Issue by k06a** [bancorprotocol/contracts-solidity#228]
Let's optimize a number of transfers avoiding transfer tokens to BancorNetwork contract. This will optimize gas at least twice.

**Comment by k06a** [comment]
Maybe BancorNetwork should use `transferFrom(msg.sender, converter, amount)` to transfer tokens directly to converter...

**Comment by yudilevi** [comment]
It might be possible to optimize the number of transfers but one thing to keep in mind is that when tokens are transferred to the converter, they actually affect the price - so need to be careful not to transfer tokens to a converter at the wrong time.

**Comment by k06a** [comment]
@yudilevi this is an important note 👍
