### ISSUE TITLE
Had a lot of failed exchanges

### ISSUE THREAD

**Issue by k06a** [bancorprotocol/contracts-solidity#233]
Made a few exchanges, all approves successed but all exchanges failed. Maybe for some reason exchanges transcations happend before appoves?

`-` [0x98eef9aa09368672cb5ed488a34adfd093e8cc9466f56ed1c3745121f49a7d49](https://etherscan.io/tx/0x98eef9aa09368672cb5ed488a34adfd093e8cc9466f56ed1c3745121f49a7d49)
`+` [0xd51f531d6e8f7caaaea1116538ff841dad195c724dfce9f47497f5fb14355811](https://etherscan.io/tx/0xd51f531d6e8f7caaaea1116538ff841dad195c724dfce9f47497f5fb14355811)
`-` [0x30a405090cfef7dd7b577ff6da63d117576bb99d047158208be357e47a9a2041](https://etherscan.io/tx/0x30a405090cfef7dd7b577ff6da63d117576bb99d047158208be357e47a9a2041)
`+` [0xda6199adf1555a4c5ac652969341637ec0f209483c5183c1787bd60ec3948bc5](https://etherscan.io/tx/0xda6199adf1555a4c5ac652969341637ec0f209483c5183c1787bd60ec3948bc5)
`-` [0xcaf0ee101b5d8aff5b4c314e7df0123ecffb180ebe729bcdb83b5ee138ce3734](https://etherscan.io/tx/0xcaf0ee101b5d8aff5b4c314e7df0123ecffb180ebe729bcdb83b5ee138ce3734)
`+` [0xd5702a4169d2556bd933c88b1af0bd9547b1e04cf8e86c1b47078e8fdd896b96](https://etherscan.io/tx/0xd5702a4169d2556bd933c88b1af0bd9547b1e04cf8e86c1b47078e8fdd896b96)
`-` [0xf7908e7264dc3a474f9b16122e562e3db24380bbcd698fda682e1462c3597c7a](https://etherscan.io/tx/0xf7908e7264dc3a474f9b16122e562e3db24380bbcd698fda682e1462c3597c7a)
`+` [0x2f5fffb37688ad39d4f9d68835b6741ab85be4813280b31fceecec227fc4baf9](https://etherscan.io/tx/0x2f5fffb37688ad39d4f9d68835b6741ab85be4813280b31fceecec227fc4baf9) 
`-` [0xc16e5c38c0e3c6cbbe741ba0fa21dd1b6745b4787493981564217e2a001aa6f4](https://etherscan.io/tx/0xc16e5c38c0e3c6cbbe741ba0fa21dd1b6745b4787493981564217e2a001aa6f4)
`+` [0xf85e43c536aa9e6c6719c198a69a9f22e22c926b3ac841e46917fca850d3e5a5](https://etherscan.io/tx/0xf85e43c536aa9e6c6719c198a69a9f22e22c926b3ac841e46917fca850d3e5a5)
`-` [0x20ce307ff058a7ab106babe61c59caec648e6c56aedda3d67cd51bd4eb908663 ](https://etherscan.io/tx/0x20ce307ff058a7ab106babe61c59caec648e6c56aedda3d67cd51bd4eb908663)

**Comment by yudilevi** [comment]
@k06a can you please provide more details about the process?
Did you do it directly on the blockchain or through the app?
What wallet did you use?

Any info will be helpful.

Thanks!

**Comment by k06a** [comment]
@yudilevi I did it using web interface of bancor.network with MetMask wallet.
