### ISSUE TITLE
Get max converted amount for a given price limit

### ISSUE THREAD

**Issue by bugduino** [bancorprotocol/contracts-solidity#261]
Hi,
I was wondering if there is a way to 'partially' convert tokens and get the maximum amount that I would get in return for converting token A to token B given a price limit.

Let's say I want to spend up to 1ETH and I want to buy some OMG tokens, but don't want to pay an unfair price for them. For this example let's assume that we have a conversion rate of 1 OMG = 0.01 ETH when converting small amounts of eth. When converting bigger amounts (eg 1ETH) the slippage is greater and the price could potentially be 0.02 ETH per OMG token. 

In this case I would like to be able to make a conversion, but without spending all the amount (1ETH) if the slippage is to high. I would like to call convert with a maximum amount spendable and a price limit (eg 0.015 eth per OMG token) and get converted only the part of the max amount that would result in a conversion with a price below the imposed price limit.

I'm thinking at something like this for `convert`:
```
    /**
        @dev converts up to _maxAmount of _fromToken to _toToken with a _priceLimit
        @param _fromToken   ERC20 token to convert from
        @param _toToken     ERC20 token to convert to
        @param _maxAmount   max amount to convert, in fromToken
        @param _priceLimit  max conversion price
        @param _minReturn   if the conversion results in an amount smaller than the minimum return - it is cancelled, must be nonzero
        @return conversion  return amount of _toToken converted
        @return rest        return amount of _fromToken not used for conversion, because price would have been > _priceLimit
    */

    function limitConvert(IERC20Token _fromToken, IERC20Token _toToken, uint256 _amount, uint256 _priceLimit, uint256 _minReturn) public returns (uint256, uint256) {
```

so a call to `limitConvert` in the example above could result in something like [80 OMG, 0.1 ETH] (in wei)  and 80 OMG is all the liquidity I got in return for 0.9 ETH with the constrain that all OMG tokens have been paid less than 0.015.

This should be similar to partially filled limit orders on traditional exchanges.
Is it already feasible?

**Comment by yudilevi** [comment]
Hey,

It's not currently supported by the contracts.
At this point I think the process would involve some kind of heuristic which isn't ideal.

It's not a bad idea to add that functionality at a later version though.

Thanks!

**Comment by bugduino** [comment]
Is there a way I could work around this issue? 
Even if the hypotetical `limitConvert` is not implemented but I'm able to calculate in some way the max token tradable below a certain price I'm just fine, because I can then properly set the correct amount in a normal `convert` call.

**Comment by yudilevi** [comment]
So you can always calculate it off-chain by reversing the bancor formula to receive the return amount as an input.
It's a bit tricker when you want to calculate it for a given path (and not just between 2 directly connected tokens) but it should be possible.

**Comment by barakman** [comment]
@yudilevi:

I believe that we have a utility for this under https://github.com/bancorprotocol/contracts/tree/master/solidity/python/Utilities/Converter.

The input for this utility consists of two input files:
1. A currency graph (see file `example_model.json`)
2. A list of operations (see file `example_commands.json`)

Using this utility, one can compute:
- `x` units of `SRC` will be converted to how many units of `DST`?
- how many units of `SRC` will be converted to `x` units of `DST`?

In the list of operations, there is no need to specify `purchase` or `sell`, because the currency graph already contains this information for any given pair of currencies.

**Comment by bugduino** [comment]
@barakman that should be already doable via a `convert` contract call (not a tx), am I right?

Let's say that I have this path ETH -> BNT -> BNT -> STORMBNT -> STORM and 
I want to know how many ETH should I invest to get my STORM tokens below a certain given price,
the formula states `Price = Reserve / CRR * Supply` how should I work this out? Should I apply it 
to every step?

**Comment by bugduino** [comment]
I was looking at the Bancor Whitepaper in the `3.3 Handling Price Slippage` section and it seems the proper way to go, is this what you @barakman were referring? The converter seems to do something very similar. If I'm using the path above how should I use that formula to get the max amount below a certain price?

**Comment by bugduino** [comment]
Hi, 
I finally had some time to rewiew this issue, I'll try to explain here the process, please correct me if I'm wrong. 
In the paper at section 3.4, we have the pricing example:
supply = 1000, conn_balance = 250, CW = 50%, token_exchanged = 10;
The effective price is 
eff_price = token_exch / token_issued = token_exch / (supply * ((1 + token_exch / conn_balance)^CW - 1)
eff_price = 10/(1000*((1+10/250)^0.5 - 1)) = 0.5054

Let's suppose instead that I want eff_price to be at most 0.501, how many token_exch can I trade?
eff_price = 0.501
token_exch/(1000*((1+token_exch/250)^0.5 - 1)) = 0.501
token_exch = 2.004
and this would issue
token_issued = 1000*((1+2.004/250)^0.5 - 1) = 4

Starting from the example above let's now suppose I have ETH and I want to buy STORM, the path is:
ETH -> BNT (smart token) -> BNT -> STORMBNT (relay token) -> STORM 

so the following conversion should happen under the hood
1) ETH -> BNT (smart token) -> BNT
2) BNT -> STORMBNT (relay) -> STORMBNT
3) STORMBNT -> STORMBNT (relay) -> STORM

In this case should I calculate the token_exch, following the example above with token_issued, for 1) and 2) and the token_exch using the connected tokens paid out for 3) ?

**Comment by maurodelazeri** [comment]
@bugduino I have the same exact question... did you manage to figure out this?

**Comment by bugduino** [comment]
@maurodelazeri I'm not working on this anymore since years sorry
