### ISSUE TITLE
Multi JSON Package Transactions

### ISSUE THREAD

**Issue by darkfireXXI** [bancorprotocol/contracts-solidity#266]
I have been trying to use Bancor's API to convert ETH to tokens and vice versa. I can successfully convert ETH to DAI and pinging the server to get other conversion rates works as explained in the API documentation (1 JSON package returned from Bancor, sign it, send it - and it works). However, when converting DAI to ETH Bancor gives back 2 JSON packages. I've extensively tried sending all sorts of combinations (eg just the first, just the second, both, both with a time delay between them, etc) and it always fails. [Note: when the transaction fails I must then make a manual transaction to "clear" the account before sending another request. If not another API conversion will result in a "Blockchain Error" from Bancor]

I've manually converted DAI to ETH on the Bancor site and notice that using the developer tools in Firefox it seems to send 3 JSON packages. This is also confirmed when the transactions show up on [etherscan.io](etherscan.io).

I'm guessing I should be receiving a third JSON package to send to my ETH node or there is some other detail not covered in the documentation as to why I can only successfully convert in one direction right now.

Code:
```
publicKey = '0x1234567890'
privateKey = '1234567890'

body = {"blockchainType":"ethereum",
"fromCurrencyId":"{}".format('5a604b62c5e04600015b72d5'), # DAI
"toCurrencyId":"{}".format('5937d635231e97001f744267'), # ETH
"amount":"1000000000000000000", # in Wei
"minimumReturn":"980000000000000000", # amount in Wei * 0.98 per Bancor's suggestion
"ownerAddress":"{}".format(publicKey)} 

w3 = Web3(HTTPProvider('https://mainnet.infura.io/v3/your_node'))

convertData = requests.post('https://api.bancor.network/0.1/currencies/convert', data=body)

account = Account()
acct = account.privateKeyToAccount(privateKey)
necessary = w3.eth.accounts

txn = convertData['data'][0] # copy paste this part again with index 1 to send the second package
txn['gas'] = convertData['data'][0]['gasLimit']
txn['to'] = Web3.toChecksumAddress(txn['to'])
del txn['gasLimit']
txn['from'] = Web3.toChecksumAddress(txn['from'])
sig = w3.eth.account.signTransaction(txn, privateKey)
confirm = w3.eth.sendRawTransaction(sig['rawTransaction'])
print(confirm.hex())
```
The two JSON packages return from Bancor are shown below:
```
{'from': '0xba2d8d08d71686b0502dcb8b221e1a535df3112c', 'to': '0xa485bd50228440797abb4d4595161d7546811160', 'data': '0x095ea7b3000000000000000000000000dda1bfaf552b0f303d27853a4a13dd440c7e849f000000000000000000000000000000000000000000000000009b69dba47c9567', 'gasPrice': '0x12a05f200', 'nonce': '0x24', 'gasLimit': '0x24a6b'}
{'from': '0xBA2d8d08d71686b0502DcB8b221E1A535DF3112C', 'to': '0xdda1bfaf552b0f303d27853a4a13dd440c7e849f', 'data': '0x2274256400000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000009b69dba47c9567000000000000000000000000000000000000000000000000009b69db888f5200000000000000000000000000000000000000000000000000000000000068bc05000000000000000000000000000000000000000000000000000000000000001c9783230cea1daacbd17fa1f22111ec1c1b9acf387a6dee53e00eb85ebdaf17635922883904c80b52f9dfce3637eee88e7eba640301764a2a3293a2bd2f3b36370000000000000000000000000000000000000000000000000000000000000005000000000000000000000000a485bd50228440797abb4d4595161d7546811160000000000000000000000000607108c46bce4cf6f86698e9b46e3270a734fefe0000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c0000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c000000000000000000000000c0829421c1d260bd3cb3e0f06cfe2d52db2ce315', 'gasLimit': '0xcf850', 'gasPrice': '0x12a05f200', 'nonce': '0x25'}]}
```

**Comment by yudilevi** [comment]
Hi,

The reason for the 2 transactions in the required allowance - the first tx is the approve call, while the 2nd is the convert call.
If you already have allowance defined for the token but the amount isn't high enough, you'll see 3 transactions - approve(0), approve(real amount), and then the convert.

You can also check out the requests/return values of the API calls the bancor webapp client invokes and compare with your own transactions.

Yudi

**Comment by darkfireXXI** [comment]
Hi Yudi,
Thanks for the response. I'm sending both transactions, but normally the first one goes through, while the second one fails - thus the entire conversion fails. What should I be doing differently?

**Comment by darkfireXXI** [comment]
The only things I've changed are gasLimit to gas and then deleting gasLimit. I have to do this as otherwise I get invalid fields when signing the package with my private key. This hasn't caused any problems when converting from ETH to DAI

**Comment by yudilevi** [comment]
Can you post a link to the failed tx?

**Comment by darkfireXXI** [comment]
[https://etherscan.io/address/0xba2d8d08d71686b0502dcb8b221e1a535df3112c](https://etherscan.io/address/0xba2d8d08d71686b0502dcb8b221e1a535df3112c)

The transactions with the red ! are the ones that failed. The transaction to "DaiStableCoin" works, but the second one to "BancorConverter_#124" always fails

**Comment by yudilevi** [comment]
I might be wrong here but I think the account doesn't have an allowance in DAI, which means that the first transaction didn't go through, can you double check that?

**Comment by darkfireXXI** [comment]
Okay, so I looked into ERC20 token allowance and ended up adding these lines of codes:

```
ERC20_ABI = json.loads('[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"address"},{"indexed":true,"name":"_to","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_owner","type":"address"},{"indexed":true,"name":"_spender","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"}]')
erc20 = w3.eth.contract(address=Web3.toChecksumAddress('0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359'), abi=ERC20_ABI)
```
Now the Bancor API returns 3 packages and sending all 3 results in two successful transactions to "DaiStableCoin" and one failed "BancorConverter_#124" seen here:
[https://etherscan.io/address/0x2D52C8C231729331DdD8dF8A31eA87601413eC99](https://etherscan.io/address/0x2D52C8C231729331DdD8dF8A31eA87601413eC99)

Not sure if this is what you meant, but I think it's a step in the right direction

**Comment by yudilevi** [comment]
The first transactions are supposed to give the converter allowance to the tokens in your account that you're trying to convert.
Can you check if the allowance was actually given? You can actually check it on etherscan by going into the `read contract` tab and filling in the addresses there.

**Comment by darkfireXXI** [comment]
Okay, I checked and found that my allowance is 0. Do you know how/where I can change that? Apparently using the ABI code I found [here](https://github.com/bancorprotocol/contracts/issues/266#issuecomment-446369970) should do it, but that didn't help

**Comment by yudilevi** [comment]
The first transaction should do that for you, so not clear what's wrong there.
However, you can also do it manually by executing `approve` on the DAI token, passing in the BancorNetwork contract address as the spender and the amount you want to convert (don't forget the decimals).
You might also want to do the same for the DAI/BNT converter as the spender, just in case.

Then try to execute the convert call and see if that works.

**Comment by darkfireXXI** [comment]
Hey, I went on [EtherScan here](https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359#writeContract) and manually approved [BancorConverter_#124](https://etherscan.io/address/0x587044b74004E3D5eF2D453b7F8d198d9e4cB558) to spend x amount of DAI. I'm not sure if this was the method you had in mind though. Anyway this has worked with some success, but often Bancor returns a "blockchainError" Once this happens I must either manually move money around from token to token until the error magically disappears or I can make a new ETH wallet, transfer money there, and try again.  

The reliability is quite bad and the error seems to be on Bancor's side delivering the JSON package. As a result I'm hoping you might know how to deal with this error:
```
data = requests.post('https://api.bancor.network/0.1/currencies/convert', data=pkg).json()
print(data)  

{'errorCode': 'blockchainError'}
```
Considering this is probably harder to resolve, I was also curious if you know how to generate the data returned upon a successful call that normally looks like this:
```
data = requests.post('https://api.bancor.network/0.1/currencies/convert', data=pkg).json()
print(data)  

{'data': [{'from': '0x3826dc800aee99966fdad9fc8384ec1d1dffb167', 'to': '0xb89570f6ad742cb1fd440a930d6c2a2ea29c51ee', 'data': '0x2274256400000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000058d15e176280000000000000000000000000000000000000000000000000000058baa15343f00000000000000000000000000000000000000000000000000000000000006a5a9b000000000000000000000000000000000000000000000000000000000000001b649c8cab8a0af45aa92ef548dd240d89f84067acf66720b25dc38d3229627c4a22dc81ef9189f9aaaebd04f64c9559aefc23cee4b2f7c22d1addfdd7f651b9900000000000000000000000000000000000000000000000000000000000000005000000000000000000000000c0829421c1d260bd3cb3e0f06cfe2d52db2ce3150000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c0000000000000000000000001f573d6fb3f13d689ff844b4ce37794d79a7ff1c000000000000000000000000ee01b3ab5f6728adc137be101d99c678938e6e7200000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359', 'value': '0x58d15e17628000', 'gasPrice': '0x218711a00', 'nonce': '0x1d', 'gasLimit': '0x7b91d'}]}
```
I can fill all the fields (from, to, value, nonce, gas, etc.) manually except data, so if you tell me how Bancor generates the value for this field I can do it myself and then sign/send it to an ETH node

**Comment by yudilevi** [comment]
Hey,

Our client uses the exact API to convert and it works fine so I'm wondering what the difference is here.
Generally, when you want to (manually or automatically) approve another spender, you first need to set the approval to 0 and then change it again - this is to prevent an attack that allows the spender to spend the funds you approve before your new approval takes place.
blockchainError from our API usually means that the transaction would fail (revert) on the blockchain if sent as is. It usually indicates the wrong approval or minimum return argument.

Yudi
