### ISSUE TITLE
Deployment script error

### ISSUE THREAD

**Issue by nirkonky** [bancorprotocol/contracts-solidity#272]
Hi,

I wanna to debug your code.
so I downloaded your code, compiled the smart contracts and trying to run the tests.
for some reason, it failed to deploy the specific contract (bancor converter factory).

after some digging, there is a problem in bancorConverter contract constructor, maybe?
Bancor Version : Master.
Node Version : 8.11.4
Npm Version : 5.6.0
Web3 Version : web3@1.0.0-beta34
Genache Version : 6.2.0

**Comment by davidbancor** [comment]
Hi nirkonky,

Thanks for reaching out, can you perhaps provide a detailed explanation of how you tried to run our tests? Note that if you're trying to run our tests with truffle and ganache, ganache has to be on port 7545, and your truffle version has to be less than v5.

Alternatively, you can run `npm test 1`, which spawns an instance of ganache in the background and runs truffle test with the correct truffle version.

Thanks

**Comment by barakman** [comment]
@nirkonky:

First of all, run `npm install` from your local repository (i.e., from the path of file `package.json`).
This will ensure that you are using the exact node-package layout intended for this version of Bancor's contract system.

When done, you can run:
- `npm test 1` in order to start `ganache-cli` alongside `truffle test`
- `npm test 2` in order to start `testrpc-sc` alongside `solidity coverage`

Alternatively, you may choose to just compile, via:
- `truffle compile`, which will generate json files
- `npm run build`, which will generate json files, and then extract from them bin and abi artifacts
Please note, however, that all artifacts are already in the repository, under `contracts/solidity/build`.

Again - each one of the options above should be executed from the path of file `package.json`.

Thanks

**Comment by nirkonky** [comment]
Hi, Thanks for the fast answer,

your tests are working good.

but when I'm trying to deploy your contracts on other project , it is not
working.

the contracts are the same..
[image: image.png]
as you can see, the code is stuck when he trying to deploy the factory
contract.
the Error :
[image: image.png]

dont know what to do..

‫בתאריך יום ב׳, 18 בפבר׳ 2019 ב-19:41 מאת ‪barakman‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by barakman** [comment]
@nirkonky:
You should do some preliminary reformatting of your message, which is rather unreadable in its current state.
Also, the details of the GitHub's reminder that you received on your email are probably not relevant in this context.

**Comment by nirkonky** [comment]
Hi, sorry for the previous post, i answered via the email, thus all the mess.

The error i got : 
```

1) Bancor Converter Test
       verifies the converter data after construction:
     o: VM Exception while processing transaction: revert
      at Function.o.fromResults (node_modules\ganache-cli\build\ganache-core.node.cli.js:10:82122)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:127898
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:108706
      at p (node_modules\ganache-cli\build\ganache-core.node.cli.js:25:108363)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:108416
      at t.default (node_modules\ganache-cli\build\ganache-core.node.cli.js:37:352539)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:109330
      at y.n.emit (node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1557017)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:2192015
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:2192038
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1556055
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:2:23243
      at f (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26418)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26460
      at qt (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:35821)
      at Object.<anonymous> (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26549)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1555976
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26130
      at i (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:41185)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1555957
      at i (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:41157)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1555928
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:2:98109
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:392
      at c (node_modules\ganache-cli\build\ganache-core.node.cli.js:25:5407)
      at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:317
      at Immediate._onImmediate (node_modules\ganache-cli\build\ganache-core.node.cli.js:25:141204)
```


this is the deployment script of the bancorConverter contracts : 
(taken from https://github.com/bancorprotocol/contracts/blob/master/solidity/test/BancorConverter.js)

i have commented sections with cause errors (//ERROR)
```

const assert = require('assert');
const ganache = require('ganache-cli');
const Web3 = require('web3');

const options = { gasPrice: 20000000000,gasLimit:6721975 };
const provider = ganache.provider(options);
var web3 = new Web3();
web3.setProvider(provider);
web3.currentProvider.setMaxListeners(300); // set listener to web3.

const fs = require('fs');
const NonStandardTokenRegistryDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/NonStandardTokenRegistryABI.json'));
const BancorNetworkDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorNetworkABI.json')); 
const ContractIdsDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/ContractIdsABI.json'));  
const BancorConverterDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorConverterABI.json')); 
const SmartTokenDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/SmartTokenABI.json'));  
const BancorFormulaDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorFormulaABI.json'));  
const BancorGasPriceLimitDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorGasPriceLimitABI.json')); 
const ContractRegistryDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/ContractRegistryABI.json')); 
const ContractFeaturesDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/ContractFeaturesABI.json'));  
const TestERC20TokenDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/TestERC20TokenABI.json'));  
const TestNonStandardERC20TokenDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/TestNonStandardERC20TokenABI.json'));  
const BancorConverterFactoryDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorConverterFactoryABI.json')); 
const BancorConverterUpgraderDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorConverterUpgraderABI.json'));  
describe('Bancor Converter Test', ()=> {
    before(async () => {
        console.log("---------------------------------");
		console.log("---------------------------------");
		console.log("---------------------------------");

		accounts = await web3.eth.getAccounts(); //get web3 accounts
		console.log(accounts);
		sender = (account) => { return { from:account, gas: '1000000' } }; 

		user = accounts[0];

        contractRegistry = await deployContract('ContractRegistry'); //deploy ContractRegistry
        contractIds = await deployContract('ContractIds'); //deploy ContractIds
        contractFeatures = await deployContract('ContractFeatures'); //deploy ContractFeatures
        let contractFeaturesId = await contractIds.methods.CONTRACT_FEATURES().call(); 
        await contractRegistry.methods.registerAddress(contractFeaturesId, contractFeatures.options.address).send(sender(user)); 

        gasPriceLimit = await deployContract('BancorGasPriceLimit',[gasPrice]); //deploy BancorGasPriceLimit
        let gasPriceLimitId = await contractIds.methods.BANCOR_GAS_PRICE_LIMIT().call();
        await contractRegistry.methods.registerAddress(gasPriceLimitId, contractFeatures.options.address).send(sender(user));

        formula = await deployContract('BancorFormula'); //deploy Bancor Formula
        let formulaId = await contractIds.methods.BANCOR_FORMULA().call();
        await contractRegistry.methods.registerAddress(formulaId, formula.options.address).send(sender(user));

        nonStandardTokenRegistry = await deployContract('NonStandardTokenRegistry'); //deploy NonStandardTokenRegistry
        let nonStandardTokenRegistryId = await contractIds.methods.NON_STANDARD_TOKEN_REGISTRY().call();
        await contractRegistry.methods.registerAddress(nonStandardTokenRegistryId, nonStandardTokenRegistry.options.address).send(sender(user));

        bancorNetwork = await deployContract('BancorNetwork',[contractRegistry.options.address]); //deploy BancorNetwork
        let bancorNetworkId = await contractIds.methods.BANCOR_NETWORK().call();
        await contractRegistry.methods.registerAddress(bancorNetworkId, bancorNetwork.options.address).send(sender(user));
        await bancorNetwork.methods.setSignerAddress(accounts[3]).send(sender(user));

		//Here the code stuck with an error that he trying to deploy bancorConverter contract without success 
		//ERROR : o: VM Exception while processing transaction: out of gas
        factory = await deployContract('BancorConverterFactory');  //deploy BancorConverterFactory
        let bancorConverterFactoryId = await contractIds.methods.BANCOR_CONVERTER_FACTORY().call();
        await contractRegistry.methods.registerAddress(bancorConverterFactoryId, factory.options.address).send(sender(user));
        console.log('----');

        upgrader = await deployContract('BancorConverterUpgrader',[contractRegistry.methods.address]); //deploy SmarBancorConverterUpgradertToken
        let bancorConverterUpgraderId = await contractIds.methods.BANCOR_CONVERTER_UPGRADER().call();
        await contractRegistry.methods.registerAddress(bancorConverterUpgraderId, upgrader.options.address).send(sender(user));

        let bancorXId = await contractIds.methods.BANCOR_X().call();
        await contractRegistry.methods.registerAddress(bancorXId, accounts[0]);
        token = await deployContract('SmartToken',['Token1', 'TKN1', 2]); //deploy SmartToken
        tokenAddress = token.options.address;
        
        connectorToken = await deployContract('TestERC20Token',['ERC Token 1', 'ERC1', 1000000000]); //deploy TestERC20Token
        connectorToken2 = await deployContract('TestNonStandardERC20Token',['ERC Token 2', 'ERC1', 2000000000]); //deploy TestNonStandardERC20Token
        connectorToken3 = await deployContract('TestERC20Token',['ERC Token 3', 'ERC1', 1500000000]); //deploy TestERC20Token

        await nonStandardTokenRegistry.methods.setAddress(connectorToken2.address, true).send(sender(user));
    });


    it('verifies the converter data after construction', async () => {
        console.log('trying to deploy BancorConverter');
		//Here the code stuck with an error that he trying to deploy bancorConverter contract without success 
		//ERROR : o: VM Exception while processing transaction: revert
        let converter = await deployContract('BancorConverter',[tokenAddress, contractRegistry.address, 0, '0x0', 0]); //deploy BancorConverter
        console.log('trying to deploy BancorConverter Finished');
        let token = await converter.methods.token().call();
        assert.equal(token, tokenAddress);
        let registry = await converter.methods.registry.call();
        assert.equal(registry, contractRegistry.address);

        let featureWhitelist = await converter.methods.CONVERTER_CONVERSION_WHITELIST().call();
        let isSupported = await contractFeatures.methods.isSupported(converter.address, featureWhitelist).call();
        assert(isSupported);

        let maxConversionFee = await converter.methods.maxConversionFee.call();
        assert.equal(maxConversionFee, 0);
        let conversionsEnabled = await converter.methodsconversionsEnabled.call();
        assert.equal(conversionsEnabled, true);
    });
	
});

Please advice.

Note: im compiled the contracts via solc library and not via truffle.

**Comment by barakman** [comment]
@nirkonky:

In your previous message, you originally (before editing it) stated the following:
> your tests are working good.but when I'm trying to deploy your contracts on other project , it is not working.

To me, this implies that the problem is due to the difference between Bancor's environment setup and your project's environment setup.

So to begin with, please make sure that your project relies on the same packages intended by Bancor.
You can start by taking a look at the `package.json` file and comparing it with yours (or with whatever setup you have in your project).

Thanks

**Comment by nirkonky** [comment]
@barakman 

yours dependencies:
```
"dependencies": {
    "decimal.js": "^10.0.2", 
    "ethereumjs-util": "^5.2.0", 
    "ganache-cli": "6.2.5", 
    "js-sha256": "^0.9.0",
    "left-pad": "^1.3.0", 
    "npm": "^6.7.0", 
    "solidity-coverage": "0.5.11", 
    "truffle": "4.1.14", 
    "truffle-contract": "^3.0.7",
    "truffle-flattener": "^1.2.10", 
    "web3-utils": "^1.0.0-beta.39" 
}
  
```


```
 my dependencies:
 "dependencies": {
  "@babel/runtime": "^7.3.1",
    "bn.js": "^4.11.8",
    "bs58": "^4.0.1",
    "chai": "^4.2.0",
    "cognito-express": "^2.0.12",
    "cryptico": "^1.0.2",
    "crypto-js": "^3.1.9-1",
    "elliptic": "^6.4.1",
    "ethereumjs-account": "^2.0.5",
    "ethereumjs-units": "^0.2.0",
    "ethers": "^4.0.12",
    "ganache-cli": "^6.2.5",
    "jasmine": "^3.3.1",
    "moment": "^2.22.2",
    "npm": "^5.6.0",
    "secp256k1": "^3.5.2",
    "solc": "^0.4.25",
    "sync-request": "^6.0.0",
    "truffle-hdwallet-provider": "0.0.6",
    "web3": "^1.0.0-beta.34",
    "websocket": "^1.0.28"
}
```

as you can see,
there is difference in those libraries:
web3@1.0.0-beta.34 >> web3-utils@1.0.0-beta.39
npm@5.6.0 >> npm@6.7.0

you are using truffle to compile and deploy the contracts.
im using solc to compile , and web3 to deploy the contracts.

to make it works , i must install and use truffle?

**Comment by barakman** [comment]
@nirkonky:

> web3@1.0.0-beta.34 >> web3-utils@1.0.0-beta.39
No difference here, since both cases use `^`, which means that `npm` brings the latest build (which I think is around 46 at present).

> npm@5.6.0 >> npm@6.7.0
If this was the cause of your problems, then I suspect that you'd experience many other problems, much more basic than what you're describing. In any case, you should probably update your `npm` (as well as your `node`) version.

> you are using truffle to compile and deploy the contracts.
Yes, but the problem that you're describing is in a Truffle test, which I don't quite see how you are executing, given the fact that you don't have Truffle installed on your system. I'm allowing myself to guess that you do actually have Truffle installed, but it is installed globally (i.e., was installed at some point in the past via `npm install truffle -g`). I can't see how you'd be able to execute `truffle test` on your system. My suggestion is that to begin with, you should add `"truffle": "4.1.14"` to your `package.json` file, and then call `npm install` in that folder.

> im using solc to compile , and web3 to deploy the contracts.
Doesn't matter. When you run `truffle test`, it starts by compiling the contracts (if you haven't explicitly executed `truffle compile` beforehand). It compiles the contracts with whatever version of solc it relies on (for example, Truffle v4.1.14 relies on solc v0.4.24). It is important to note, however, that Truffle v4.x relies on web3 v0.x, so your version of web3 has in fact no impact on the execution of the tests via Truffle.

Thanks

**Comment by nirkonky** [comment]
@barakman 
before I'm downloading truffle and trying to compile + deploy the contracts with truffle.

this is how i compile each contract : 
```
const path = require('path');
const fs = require('fs');
const solc = require('solc');

var input = {};

var filesUnderContracts = fs.readdirSync('contracts');

for(var i=0;i<filesUnderContracts.length;i++){
    if(filesUnderContracts[i]!='bancorx' && filesUnderContracts[i]!='BridgezContracts' && filesUnderContracts[i]!='converter'
    && filesUnderContracts[i]!='crowdsale' && filesUnderContracts[i]!='helpers' && filesUnderContracts[i]!='legacy'
    && filesUnderContracts[i]!='token' && filesUnderContracts[i]!='utility'){
        input[filesUnderContracts[i]] = fs.readFileSync('contracts/'+filesUnderContracts[i],'utf8');
    }
}
var filesUnderHelpers = fs.readdirSync('contracts/helpers');
for(var i=0;i<filesUnderHelpers.length;i++){
    if(filesUnderHelpers[i]!='interfaces'){
        input['helpers/'+filesUnderHelpers[i]] = fs.readFileSync('contracts/helpers/'+filesUnderHelpers[i],'utf8');
    }else{
        var filesUnderInterfacesHelpers = fs.readdirSync('contracts/helpers/interfaces');
        for(var j=0;j<filesUnderInterfacesHelpers.length;j++){
            input['helpers/interfaces/'+filesUnderInterfacesHelpers[j]] = fs.readFileSync('contracts/helpers/interfaces/'+filesUnderInterfacesHelpers[j],'utf8');
        }
    }
    
}

var filesUnderBancorX = fs.readdirSync('contracts/bancorx');
for(var i=0;i<filesUnderBancorX.length;i++){
    if(filesUnderBancorX[i]!='interfaces'){
        input['bancorx/'+filesUnderBancorX[i]] = fs.readFileSync('contracts/bancorx/'+filesUnderBancorX[i],'utf8');
    }else{
        var filesUnderInterfacesBancorX = fs.readdirSync('contracts/bancorx/interfaces');
        for(var j=0;j<filesUnderInterfacesBancorX.length;j++){
            input['bancorx/interfaces/'+filesUnderInterfacesBancorX[j]] = fs.readFileSync('contracts/bancorx/interfaces/'+filesUnderInterfacesBancorX[j],'utf8');
        }
        
    }
    
}


var filesUnderConverter = fs.readdirSync('contracts/converter');
for(var i=0;i<filesUnderConverter.length;i++){
    if(filesUnderConverter[i]!='interfaces'){
        input['converter/'+filesUnderConverter[i]] = fs.readFileSync('contracts/converter/'+filesUnderConverter[i],'utf8');
    }else{
        var filesUnderInterfacesConverter = fs.readdirSync('contracts/converter/interfaces');
        for(var j=0;j<filesUnderInterfacesConverter.length;j++){
            input['converter/interfaces/'+filesUnderInterfacesConverter[j]] = fs.readFileSync('contracts/converter/interfaces/'+filesUnderInterfacesConverter[j],'utf8');
        }
    }
}

var filesUnderCrowdsale = fs.readdirSync('contracts/crowdsale');
for(var i=0;i<filesUnderCrowdsale.length;i++){
    if(filesUnderCrowdsale[i]!='interfaces'){
        input['crowdsale/'+filesUnderCrowdsale[i]] = fs.readFileSync('contracts/crowdsale/'+filesUnderCrowdsale[i],'utf8');
    }else{
        var filesUnderInterfacesCrowdsale = fs.readdirSync('contracts/crowdsale/interfaces');
        for(var j=0;j<filesUnderInterfacesCrowdsale.length;j++){
            input['crowdsale/interfaces/'+filesUnderInterfacesCrowdsale[j]] = fs.readFileSync('contracts/crowdsale/interfaces/'+filesUnderInterfacesCrowdsale[j],'utf8');
        }
    }
    
}


var filesUnderLegacy = fs.readdirSync('contracts/legacy');
for(var i=0;i<filesUnderLegacy.length;i++){
    if(filesUnderLegacy[i]!='interfaces'){
        input['legacy/'+filesUnderLegacy[i]] = fs.readFileSync('contracts/legacy/'+filesUnderLegacy[i],'utf8');
    }else{
        var filesUnderInterfacesLegacy = fs.readdirSync('contracts/legacy/interfaces');
        for(var j=0;j<filesUnderInterfacesLegacy.length;j++){
            input['legacy/interfaces/'+filesUnderInterfacesLegacy[j]] = fs.readFileSync('contracts/legacy/interfaces/'+filesUnderInterfacesLegacy[j],'utf8');
        }
    }
    
}
var filesUnderToken = fs.readdirSync('contracts/token');
console.log(filesUnderToken);
for(var i=0;i<filesUnderToken.length;i++){
    if(filesUnderToken[i]!='interfaces'){
        input['token/'+filesUnderToken[i]] = fs.readFileSync('contracts/token/'+filesUnderToken[i],'utf8');
    }else{
        var filesUnderInterfacesToken = fs.readdirSync('contracts/token/interfaces');
        for(var j=0;j<filesUnderInterfacesToken.length;j++){
            input['token/interfaces/'+filesUnderInterfacesToken[j]] = fs.readFileSync('contracts/token/interfaces/'+filesUnderInterfacesToken[j],'utf8');
        }
    }
}

var filesUnderUtility = fs.readdirSync('contracts/utility');
console.log(filesUnderUtility);
for(var i=0;i<filesUnderUtility.length;i++){
    if(filesUnderUtility[i]!='interfaces'){
        input['utility/'+filesUnderUtility[i]] = fs.readFileSync('contracts/utility/'+filesUnderUtility[i],'utf8');
    }else{
        var filesUnderInterfacesUtility = fs.readdirSync('contracts/utility/interfaces');
        for(var j=0;j<filesUnderInterfacesUtility.length;j++){
            input['utility/interfaces/'+filesUnderInterfacesUtility[j]] = fs.readFileSync('contracts/utility/interfaces/'+filesUnderInterfacesUtility[j],'utf8');
        }
    }
    
}


console.log('	------ Compiling... ');
let out = solc.compile({sources: input}, 1);
console.log('	------ Done compiling. \n', out.errors);
```

as you can see here, I move on each Smart Contract / Interface and compile it.
after all the smart contracts are compiled.
I read each `{ interface, bytecode } ` from the compiled ABI contracts and create a contract instance.

there is a difference between compile with solc OR with truffle?

**Comment by barakman** [comment]
@nirkonky:

Here is the way these errors are usually approached:

First of all, the error that you received is:
```
verifies the converter data after construction:
     o: VM Exception while processing transaction: revert
```

So search for `verifies the converter data after construction:` in all of the test (js) files.

Now that you've found it, check which line within this specific `it` might cause the error.

If there are several such lines, then you can add a printout before and after each line, so you can spot the erroneous line.

Now that you've found this line, check which contract function is responsible for this, and find it in the contract (sol) files.

Now that you've found the function, observe the original error - `VM Exception while processing transaction: revert` can occur only as a result of `require(some false condition)`.

You mission at this point is to find the "rogue" `require` statement. If there is more then one such statement, then you can do so by masking all but one, running the test again and repeat the process until you pinpoint the right `require` statement.

Now look at the condition inside that statement. Whatever variables are in it, you have most likely sent from your test to the contract function (this is the case for `require`, which is designated for catching illegal user-input).

Go back to the test file, and print this value right before you pass it to the contract function.
At this point, you should be able to understand why you are receiving the error.

I hope that you'll find this contract-debugging lesson fruitful...

**Comment by davidbancor** [comment]
> Hi, sorry for the previous post, i answered via the email, thus all the mess.
> 
> The error i got :
> 
> ```
> 
> 1) Bancor Converter Test
>        verifies the converter data after construction:
>      o: VM Exception while processing transaction: revert
>       at Function.o.fromResults (node_modules\ganache-cli\build\ganache-core.node.cli.js:10:82122)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:127898
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:108706
>       at p (node_modules\ganache-cli\build\ganache-core.node.cli.js:25:108363)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:108416
>       at t.default (node_modules\ganache-cli\build\ganache-core.node.cli.js:37:352539)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:109330
>       at y.n.emit (node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1557017)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:2192015
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:2192038
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1556055
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:2:23243
>       at f (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26418)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26460
>       at qt (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:35821)
>       at Object.<anonymous> (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26549)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1555976
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:2:26130
>       at i (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:41185)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1555957
>       at i (node_modules\ganache-cli\build\ganache-core.node.cli.js:2:41157)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:37:1555928
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:2:98109
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:392
>       at c (node_modules\ganache-cli\build\ganache-core.node.cli.js:25:5407)
>       at node_modules\ganache-cli\build\ganache-core.node.cli.js:25:317
>       at Immediate._onImmediate (node_modules\ganache-cli\build\ganache-core.node.cli.js:25:141204)
> ```
> this is the deployment script of the bancorConverter contracts :
> (taken from https://github.com/bancorprotocol/contracts/blob/master/solidity/test/BancorConverter.js)
> 
> i have commented sections with cause errors (//ERROR)
> 
> ```
> 
> const assert = require('assert');
> const ganache = require('ganache-cli');
> const Web3 = require('web3');
> 
> const options = { gasPrice: 20000000000,gasLimit:6721975 };
> const provider = ganache.provider(options);
> var web3 = new Web3();
> web3.setProvider(provider);
> web3.currentProvider.setMaxListeners(300); // set listener to web3.
> 
> const fs = require('fs');
> const NonStandardTokenRegistryDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/NonStandardTokenRegistryABI.json'));
> const BancorNetworkDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorNetworkABI.json')); 
> const ContractIdsDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/ContractIdsABI.json'));  
> const BancorConverterDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorConverterABI.json')); 
> const SmartTokenDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/SmartTokenABI.json'));  
> const BancorFormulaDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorFormulaABI.json'));  
> const BancorGasPriceLimitDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorGasPriceLimitABI.json')); 
> const ContractRegistryDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/ContractRegistryABI.json')); 
> const ContractFeaturesDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/ContractFeaturesABI.json'));  
> const TestERC20TokenDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/TestERC20TokenABI.json'));  
> const TestNonStandardERC20TokenDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/TestNonStandardERC20TokenABI.json'));  
> const BancorConverterFactoryDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorConverterFactoryABI.json')); 
> const BancorConverterUpgraderDeploy = JSON.parse(fs.readFileSync(appRoot+'/build/BancorConverterUpgraderABI.json'));  
> describe('Bancor Converter Test', ()=> {
>     before(async () => {
>         console.log("---------------------------------");
> 		console.log("---------------------------------");
> 		console.log("---------------------------------");
> 
> 		accounts = await web3.eth.getAccounts(); //get web3 accounts
> 		console.log(accounts);
> 		sender = (account) => { return { from:account, gas: '1000000' } }; 
> 
> 		user = accounts[0];
> 
>         contractRegistry = await deployContract('ContractRegistry'); //deploy ContractRegistry
>         contractIds = await deployContract('ContractIds'); //deploy ContractIds
>         contractFeatures = await deployContract('ContractFeatures'); //deploy ContractFeatures
>         let contractFeaturesId = await contractIds.methods.CONTRACT_FEATURES().call(); 
>         await contractRegistry.methods.registerAddress(contractFeaturesId, contractFeatures.options.address).send(sender(user)); 
> 
>         gasPriceLimit = await deployContract('BancorGasPriceLimit',[gasPrice]); //deploy BancorGasPriceLimit
>         let gasPriceLimitId = await contractIds.methods.BANCOR_GAS_PRICE_LIMIT().call();
>         await contractRegistry.methods.registerAddress(gasPriceLimitId, contractFeatures.options.address).send(sender(user));
> 
>         formula = await deployContract('BancorFormula'); //deploy Bancor Formula
>         let formulaId = await contractIds.methods.BANCOR_FORMULA().call();
>         await contractRegistry.methods.registerAddress(formulaId, formula.options.address).send(sender(user));
> 
>         nonStandardTokenRegistry = await deployContract('NonStandardTokenRegistry'); //deploy NonStandardTokenRegistry
>         let nonStandardTokenRegistryId = await contractIds.methods.NON_STANDARD_TOKEN_REGISTRY().call();
>         await contractRegistry.methods.registerAddress(nonStandardTokenRegistryId, nonStandardTokenRegistry.options.address).send(sender(user));
> 
>         bancorNetwork = await deployContract('BancorNetwork',[contractRegistry.options.address]); //deploy BancorNetwork
>         let bancorNetworkId = await contractIds.methods.BANCOR_NETWORK().call();
>         await contractRegistry.methods.registerAddress(bancorNetworkId, bancorNetwork.options.address).send(sender(user));
>         await bancorNetwork.methods.setSignerAddress(accounts[3]).send(sender(user));
> 
> 		//Here the code stuck with an error that he trying to deploy bancorConverter contract without success 
> 		//ERROR : o: VM Exception while processing transaction: out of gas
>         factory = await deployContract('BancorConverterFactory');  //deploy BancorConverterFactory
>         let bancorConverterFactoryId = await contractIds.methods.BANCOR_CONVERTER_FACTORY().call();
>         await contractRegistry.methods.registerAddress(bancorConverterFactoryId, factory.options.address).send(sender(user));
>         console.log('----');
> 
>         upgrader = await deployContract('BancorConverterUpgrader',[contractRegistry.methods.address]); //deploy SmarBancorConverterUpgradertToken
>         let bancorConverterUpgraderId = await contractIds.methods.BANCOR_CONVERTER_UPGRADER().call();
>         await contractRegistry.methods.registerAddress(bancorConverterUpgraderId, upgrader.options.address).send(sender(user));
> 
>         let bancorXId = await contractIds.methods.BANCOR_X().call();
>         await contractRegistry.methods.registerAddress(bancorXId, accounts[0]);
>         token = await deployContract('SmartToken',['Token1', 'TKN1', 2]); //deploy SmartToken
>         tokenAddress = token.options.address;
>         
>         connectorToken = await deployContract('TestERC20Token',['ERC Token 1', 'ERC1', 1000000000]); //deploy TestERC20Token
>         connectorToken2 = await deployContract('TestNonStandardERC20Token',['ERC Token 2', 'ERC1', 2000000000]); //deploy TestNonStandardERC20Token
>         connectorToken3 = await deployContract('TestERC20Token',['ERC Token 3', 'ERC1', 1500000000]); //deploy TestERC20Token
> 
>         await nonStandardTokenRegistry.methods.setAddress(connectorToken2.address, true).send(sender(user));
>     });
> 
> 
>     it('verifies the converter data after construction', async () => {
>         console.log('trying to deploy BancorConverter');
> 		//Here the code stuck with an error that he trying to deploy bancorConverter contract without success 
> 		//ERROR : o: VM Exception while processing transaction: revert
>         let converter = await deployContract('BancorConverter',[tokenAddress, contractRegistry.address, 0, '0x0', 0]); //deploy BancorConverter
>         console.log('trying to deploy BancorConverter Finished');
>         let token = await converter.methods.token().call();
>         assert.equal(token, tokenAddress);
>         let registry = await converter.methods.registry.call();
>         assert.equal(registry, contractRegistry.address);
> 
>         let featureWhitelist = await converter.methods.CONVERTER_CONVERSION_WHITELIST().call();
>         let isSupported = await contractFeatures.methods.isSupported(converter.address, featureWhitelist).call();
>         assert(isSupported);
> 
>         let maxConversionFee = await converter.methods.maxConversionFee.call();
>         assert.equal(maxConversionFee, 0);
>         let conversionsEnabled = await converter.methodsconversionsEnabled.call();
>         assert.equal(conversionsEnabled, true);
>     });
> 	
> });
> ```
> Please advice.
> 
> Note: im compiled the contracts via solc library and not via truffle.

Shouldn't it be contractRegistry.options.address rather than contractRegistry.address since you're using web3.eth.Contract and not truffle-contract? Perhaps that's what's causing the issue.

**Comment by barakman** [comment]
In short, running these tests with anything higher than web3.js v0.x will likely cause them to break.

The testing infrastructure is designated to be used under Truffle v4.1.14, which relies on Solc v0.4.24 and Web3 v0.18.4.

It will probably work correctly also under Truffle v4.1.15, which relies on Solc v0.4.25 and Web3 v0.20.6.

Switching to either Solc v0.5.x or Web3 v.1.x is not guaranteed to work (in fact, it is probably guaranteed not to work).
